### ISSUE TITLE
Is it working on OpenMediaVault 6 ?

### ISSUE THREAD

**Issue by iPeeZz** [LordZeuss/raspi-docker#3]
Hello,
This is probably a stupid question but I am completely new to this and was wondering if this works on "OpenMediaVault" ? I assume it does because "OpenMediaVault" is Debian based but I'd like to get confirmation and if so where do I enter the command lines? Is it on the "OpenMediaVault" "Wetty" plugin ?

Thanks in advance and sorry for the inconvenience.

**Comment by LordZeuss** [comment]
Sorry for the late reply. I have not tested it on openmediavault but it being Debian based gives me hope. Usually you would input these commands in a shell/terminal of some sorts, and depending on the OS and its use case, there might not be a shell, or it may be locked down, opposed to regular Debian based desktop/server distros.

I can look into testing myself, but for now I would look into if you can run shell commands on openmediavault, and if you do find that these scripts do or do not work, please let me know so that way I can add it to the README that it does/doesn't work with that particular distro.

Additionally, if openmediavault can run a virtual machine, spin up a normal Debian based distribution of Linux and run these scripts on there. If openmediavault does not have that capability, TrueNAS scale does offer virtual machine capabilities and you could spin up a VM for this, but it's ultimately up to you how you would like to go about it.

**Comment by iPeeZz** [comment]
Thank you for your answer unfortunately I can't test this at the moment but from what I could see it seems that OpenMediaVault can launch commands via a Shell it's called Wetty in the OpenMediaVault plugins page, I'll probably test as soon as I have the possibility and give you a feedback at that time, even if I imagine that you'll have already tested yourself at that time.
